name: Dependabot auto-merge

permissions:
  contents: read

on:
  pull_request:

jobs:
  dependabot:
    permissions:
      contents: write
      pull-requests: write
    uses: go-openapi/ci-workflows/.github/workflows/auto-merge.yml@19b4bfa40f3712057a6ffc78763b2feb75ee94d9 # v0.3.1
    secrets: inherit
