name: Contributors

on:
  schedule:
    - cron: '18 4 * * 6'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  contributors:
    permissions:
      pull-requests: write
      contents: write
    uses: go-openapi/ci-workflows/.github/workflows/contributors.yml@19b4bfa40f3712057a6ffc78763b2feb75ee94d9 # v0.3.1
    secrets: inherit
