name: go test

permissions:
  pull-requests: read
  contents: read

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  test:
    uses: go-openapi/ci-workflows/.github/workflows/go-test-monorepo.yml@19b4bfa40f3712057a6ffc78763b2feb75ee94d9 # v0.3.1
    secrets: inherit
