name: integration test

permissions:
  pull-requests: read
  contents: read

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run integration tests
        working-directory: internal/testintegration
        env:
          MONGODB_URI: mongodb://localhost:27017
        run: go test -tags testintegration -v -count=1 ./...
