name: Monitor bot PRs

on:
  workflow_dispatch:
  schedule:
    - cron: '18 6 * * *'

permissions:
  contents: read

jobs:
  monitor-pr:
    permissions:
      contents: write
      pull-requests: write
      statuses: read
    uses: go-openapi/ci-workflows/.github/workflows/monitor-bot-pr.yml@f3de433eeb102475ff4f5c5b2f19e25af8731ad0 # v0.3.2
    secrets: inherit
