name: Monitor bot PRs

on:
  workflow_dispatch:
  schedule:
    - cron: '18 6 * * *'

permissions:
  contents: read

jobs:
  monitor-pr:
    permissions:
      contents: write
      pull-requests: write
      statuses: read
    uses: go-openapi/ci-workflows/.github/workflows/monitor-bot-pr.yml@7370d55bb3951603c2292df3dd8a11ae7030afa7 # v0.3.3
    secrets: inherit
