name: Vulnerability scans

on:
  branch_protection_rule:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '18 4 * * 3'

permissions:
  contents: read

jobs:
  scanners:
    permissions:
      contents: read
      security-events: write
    uses: go-openapi/ci-workflows/.github/workflows/scanner.yml@19b4bfa40f3712057a6ffc78763b2feb75ee94d9 # v0.3.1
    secrets: inherit
