name: Release on tag

permissions:
  contents: read

on:
  push:
    tags:
      - v[0-9]+*

jobs:
  gh-release:
    name: Create release
    permissions:
      contents: write
    uses: go-openapi/ci-workflows/.github/workflows/release.yml@i7370d55bb3951603c2292df3dd8a11ae7030afa7 # v0.3.3
    with:
      tag: ${{ github.ref_name }}
      is-monorepo: true
    secrets: inherit
